[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_LWIP_IP_FORWARD=1
    -DCONFIG_LWIP_IPV4_NAPT=1
    -DCONFIG_LWIP_L2_TO_L3_COPY=1

build_src_filter =
    +<*>

[env:esp32dev_test]
extends = env:esp32dev
test_build_src = yes
build_src_filter =
    ${env:esp32dev.build_src_filter}
    -<main.cpp>
